name: Documentation

on:
  push:
    branches: [ master ]

jobs:
  document:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Elixir
      uses: actions/setup-elixir@v1.2.0
      with:
        elixir-version: 1.9
        otp-version: 20
        install-hex: true
        install-rebar: false

    - name: Get mix set up.
      run: mix deps.get

    - name: Run ExDoc.
      run: mix docs
    
    - name: Publish to Github Pages
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        keep_history: true
        build_dir: doc
        committer_name: "github pages bot"
        commit_message: "Deploy documentation."
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
